import { NextRequest, NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { execSync } from 'child_process';
import { PrismaClient, prisma } from '@ems/database';
import { hashPassword } from '@ems/auth';
import { PERMISSIONS, PERMISSION_DEFINITIONS } from '@ems/shared';
import { enforceRateLimit } from '@/lib/rate-limit';
import { getCurrentUser } from '@/lib/auth-guard';
import { safeErrorResponse } from '@/lib/safe-error';

export const dynamic = 'force-dynamic';

export async function POST(req: NextRequest) {
  // 1. Rate limiting: max 3 setup executions per 10 minutes
  const rateLimitError = await enforceRateLimit(req, { limit: 3, windowMs: 10 * 60 * 1000, prefix: 'setup-exec' });
  if (rateLimitError) return rateLimitError;

  let client: PrismaClient | null = null;
  try {
    const rootDir = process.cwd();
    const installedFilePath = path.join(rootDir, '.installed');
    const rootInstalledFilePath = path.join(rootDir, '..', '..', '.installed');

    const fileInstalled = fs.existsSync(installedFilePath) || fs.existsSync(rootInstalledFilePath);

    // If installed file already exists, require superadmin session
    if (fileInstalled) {
      const user = await getCurrentUser(req);
      if (!user || !user.roles?.includes('admin')) {
        return NextResponse.json(
          { success: false, error: 'Система уже установлена. Повторная инициализация заблокирована.' },
          { status: 403 }
        );
      }
    }

    const body = await req.json();
    const {
      dbConfig,
      adminConfig,
      ldapConfig,
      storageConfig,
      jiraConfig,
    } = body;

    const isLdapAuth = Boolean(
      adminConfig?.authType === 'ldap' ||
      ldapConfig?.authType === 'ldap' ||
      (ldapConfig?.enabled && ldapConfig?.useForAdmin)
    );

    if (!adminConfig?.login) {
      return NextResponse.json(
        { success: false, error: 'Укажите логин супер-администратора' },
        { status: 400 }
      );
    }

    if (!isLdapAuth && !adminConfig?.password) {
      return NextResponse.json(
        { success: false, error: 'Укажите пароль супер-администратора для локальной базы данных' },
        { status: 400 }
      );
    }

    // -------------------------------------------------------------------------
    // Pre-flight dependency validation
    // -------------------------------------------------------------------------
    const nodeMajor = parseInt(process.versions.node.split('.')[0] || '0', 10);
    if (nodeMajor < 18) {
      return NextResponse.json(
        { success: false, error: 'Установка заблокирована: версия Node.js ниже 18.0.0. Обновите Node.js.' },
        { status: 400 }
      );
    }

    const storagePath = path.resolve(storageConfig?.dir || process.env.STORAGE_LOCAL_DIR || path.join(rootDir, 'uploads'));
    try {
      if (!fs.existsSync(storagePath)) {
        fs.mkdirSync(storagePath, { recursive: true });
      }
      const testFile = path.join(storagePath, `.perm_test_${Date.now()}.tmp`);
      fs.writeFileSync(testFile, 'test');
      fs.unlinkSync(testFile);
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      return NextResponse.json(
        { success: false, error: `Установка заблокирована: каталог хранилища недоступен для записи (${storagePath}): ${errorMessage}` },
        { status: 400 }
      );
    }

    try {
      crypto.randomBytes(32);
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      return NextResponse.json(
        { success: false, error: `Установка заблокирована: ошибка генерации криптографической энтропии: ${errorMessage}` },
        { status: 400 }
      );
    }

    // Build database URL
    let dbUrl = dbConfig?.url?.trim();
    if (!dbUrl) {
      const host = dbConfig?.host || process.env.DB_HOST || 'localhost';
      const port = dbConfig?.port || '5432';
      const user = dbConfig?.user || 'postgres';
      const pass = dbConfig?.password || '';
      const database = dbConfig?.database || 'ems_db';
      const authStr = pass ? `${encodeURIComponent(user)}:${encodeURIComponent(pass)}` : encodeURIComponent(user);
      dbUrl = `postgresql://${authStr}@${host}:${port}/${database}`;
    }

    // 4. Update .env files first so Prisma loads the correct DATABASE_URL
    const jwtSecret = process.env.JWT_SECRET || crypto.randomBytes(32).toString('hex');
    const storageDir = storageConfig?.dir || './uploads';
    const jiraHost = jiraConfig?.host || jiraConfig?.baseUrl || '';
    const jiraEmail = jiraConfig?.email || jiraConfig?.userEmail || '';
    const envLines = [
      `# EMS Platform Configuration Generated by Setup Wizard on ${new Date().toISOString()}`,
      `DATABASE_URL="${dbUrl}"`,
      `JWT_SECRET="${jwtSecret}"`,
      `JWT_EXPIRES_IN="8h"`,
      `JWT_EXPIRATION="8h"`,
      ``,
      `# Storage Configuration`,
      `STORAGE_TYPE="local"`,
      `STORAGE_LOCAL_DIR="${storageDir}"`,
      `UPLOAD_DIR="${storageDir}"`,
      ``,
      `# LDAP / Active Directory Integration`,
      `LDAP_ENABLED="${ldapConfig?.enabled ? 'true' : 'false'}"`,
      `LDAP_URL="${ldapConfig?.url || ''}"`,
      `LDAP_BIND_DN="${ldapConfig?.bindDn || ''}"`,
      `LDAP_BIND_PASSWORD="${ldapConfig?.bindPassword || ''}"`,
      `LDAP_SEARCH_BASE="${ldapConfig?.searchBase || ''}"`,
      `LDAP_SEARCH_FILTER="${ldapConfig?.searchFilter || '(sAMAccountName={{username}})'}"`,
      ``,
      `# Jira SRM Integration`,
      `JIRA_HOST="${jiraHost}"`,
      `JIRA_BASE_URL="${jiraHost}"`,
      `JIRA_EMAIL="${jiraEmail}"`,
      `JIRA_USER_EMAIL="${jiraEmail}"`,
      `JIRA_API_TOKEN="${jiraConfig?.apiToken || ''}"`,
      `JIRA_PROJECT_KEY="${jiraConfig?.projectKey || 'EMS'}"`,
      ``,
    ].join('\n');

    try {
      // Write to project root .env and apps/web .env
      const rootEnvPath = path.join(rootDir, '..', '..', '.env');
      const webEnvPath = path.join(rootDir, '.env');
      if (fs.existsSync(path.dirname(rootEnvPath))) {
        fs.writeFileSync(rootEnvPath, envLines, 'utf-8');
      }
      fs.writeFileSync(webEnvPath, envLines, 'utf-8');
    } catch (envErr) {
      console.warn('Could not write to disk .env:', envErr);
    }

    // Automatically synchronize database schema if schema.prisma is found
    try {
      const potentialSchemaPaths = [
        path.join(rootDir, 'packages', 'database', 'prisma', 'schema.prisma'),
        path.join(rootDir, '..', '..', 'packages', 'database', 'prisma', 'schema.prisma'),
        path.join(rootDir, 'prisma', 'schema.prisma'),
        path.join(rootDir, '..', 'packages', 'database', 'prisma', 'schema.prisma'),
      ];
      const schemaPath = potentialSchemaPaths.find((p) => fs.existsSync(p));
      if (schemaPath) {
        const schemaDir = path.dirname(path.dirname(schemaPath));
        try {
          fs.writeFileSync(path.join(schemaDir, '.env'), `DATABASE_URL="${dbUrl}"\n`, 'utf-8');
        } catch {}

        const prismaCmd = process.platform === 'win32' ? 'npx.cmd' : 'npx';
        execSync(`${prismaCmd} prisma db push --schema="${schemaPath}" --accept-data-loss --skip-generate`, {
          cwd: schemaDir,
          env: {
            ...process.env,
            DATABASE_URL: dbUrl,
          },
          stdio: 'pipe',
          timeout: 60000,
          shell: true as any,
        });
      }
    } catch (schemaSyncErr: unknown) {
      const commandError = schemaSyncErr as { message?: string; stderr?: Buffer | string };
      console.error('Database schema sync error:', commandError.message || schemaSyncErr);
      const stderr = commandError.stderr?.toString() || commandError.message || String(schemaSyncErr);
      return NextResponse.json(
        {
          success: false,
          error: `Ошибка создания схемы таблиц в базе данных: ${stderr}`,
        },
        { status: 400 }
      );
    }

    // Initialize temporary PrismaClient with the target database URL
    client = new PrismaClient({
      datasources: {
        db: {
          url: dbUrl,
        },
      },
    });

    // 1. Ensure all system permissions exist with rich descriptions
    for (const [code, def] of Object.entries(PERMISSION_DEFINITIONS)) {
      await client.permission.upsert({
        where: { code },
        create: {
          code: def.code,
          displayName: def.displayName,
          module: def.module,
          description: def.description,
        },
        update: {
          displayName: def.displayName,
          description: def.description,
          module: def.module,
        },
      });
    }

    // 2. Ensure default roles exist
    const allDbPermissions = await client.permission.findMany();
    const adminRole = await client.role.upsert({
      where: { name: 'admin' },
      create: {
        name: 'admin',
        displayName: 'Администратор',
        description: 'Полный доступ ко всем модулям и настройкам системы',
        isSystem: true,
      },
      update: {},
    });

    // Link all permissions to admin role
    for (const perm of allDbPermissions) {
      await client.rolePermission.upsert({
        where: {
          roleId_permissionId: {
            roleId: adminRole.id,
            permissionId: perm.id,
          },
        },
        create: {
          roleId: adminRole.id,
          permissionId: perm.id,
        },
        update: {},
      });
    }

    // 3. Create or update the Superadmin User (passwordHash is NULL when authenticated via LDAP)
    const passwordHash = isLdapAuth ? null : (adminConfig.password ? hashPassword(adminConfig.password) : null);
    const superadmin = await client.user.upsert({
      where: { ldapLogin: adminConfig.login.trim().toLowerCase() },
      create: {
        ldapLogin: adminConfig.login.trim().toLowerCase(),
        displayName: adminConfig.displayName?.trim() || 'Главный Администратор',
        email: adminConfig.email?.trim() || null,
        passwordHash,
        isActive: true,
      },
      update: {
        passwordHash,
        displayName: adminConfig.displayName?.trim() || undefined,
        email: adminConfig.email?.trim() || undefined,
        isActive: true,
      },
    });

    // Assign admin role to superadmin
    await client.userRole.upsert({
      where: {
        userId_roleId: {
          userId: superadmin.id,
          roleId: adminRole.id,
        },
      },
      create: {
        userId: superadmin.id,
        roleId: adminRole.id,
      },
      update: {},
    });

    // 4. Save system settings to database
    const settingsToSave = [
      { key: 'LDAP_ENABLED', value: (ldapConfig?.enabled || isLdapAuth) ? 'true' : 'false', description: 'Служба каталогов LDAP включена' },
      { key: 'LDAP_URL', value: ldapConfig?.url || '', description: 'URL сервера LDAP' },
      { key: 'LDAP_SEARCH_BASE', value: ldapConfig?.searchBase || '', description: 'Search Base LDAP' },
      { key: 'LDAP_SEARCH_FILTER', value: ldapConfig?.searchFilter || '(|(sAMAccountName={{username}})(uid={{username}})(userPrincipalName={{username}}))', description: 'Фильтр поиска LDAP' },
      { key: 'LDAP_BIND_DN', value: ldapConfig?.bindDn || '', description: 'Bind DN' },
      { key: 'STORAGE_LOCAL_DIR', value: storageDir, description: 'Каталог хранилища файлов' },
      { key: 'JIRA_BASE_URL', value: jiraHost, description: 'URL внешней SRM/Jira' },
      { key: 'JIRA_PROJECT_KEY', value: jiraConfig?.projectKey || 'EMS', description: 'Ключ проекта SRM/Jira' },
    ];

    for (const s of settingsToSave) {
      await client.systemSetting.upsert({
        where: { key: s.key },
        create: {
          key: s.key,
          value: s.value,
          description: s.description,
        },
        update: {
          value: s.value,
          description: s.description,
        },
      });
    }

    // 5. Create .installed lock file
    try {
      const installMeta = JSON.stringify(
        {
          installedAt: new Date().toISOString(),
          superadminLogin: superadmin.ldapLogin,
          dbUrlTested: true,
        },
        null,
        2
      );
      fs.writeFileSync(installedFilePath, installMeta, 'utf-8');
      const rootInstallMeta = path.join(rootDir, '..', '..', '.installed');
      if (fs.existsSync(path.dirname(rootInstallMeta))) {
        fs.writeFileSync(rootInstallMeta, installMeta, 'utf-8');
      }
    } catch (lockErr) {
      console.warn('Could not write .installed marker:', lockErr);
    }

    return NextResponse.json({
      success: true,
      message: 'Система EMS успешно установлена и готова к работе!',
      redirect: '/login',
    });
  } catch (error: unknown) {
    return safeErrorResponse(error, 'Ошибка во время выполнения установки', 500, { endpoint: 'setup-execute' });
  } finally {
    if (client) {
      await client.$disconnect().catch(() => {});
    }
  }
}
